sudo: required
services:
  - docker

before_install:
  - docker build -t adek676/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adek676/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "udemy-docker"
  enf: "Udemy-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-000935017569"
  bucket_path: "udemy-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
    